=== Eduin321/Eduin321-Ejercicios_Xml_Dtd_Xsd/Ejercicio2/Inforeglas.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="numeroserie" type="xs:string" maxOccurs="1"/>
                            <xs:element name="cantidad" type="xs:string" maxOccurs="1"/>
                            <xs:element name="peso" type="xs:string" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Eduin321/Eduin321-Ejercicios_Xml_Dtd_Xsd/Ejercicio2/Pedidos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "pedidosreglas.dtd">
<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="Inforeglas.xsd">
    <pedido>
        <numeroserie>15455</numeroserie>
        <cantidad>8</cantidad>
        <peso>900</peso>
    </pedido>
    <pedido>
        <numeroserie>161818</numeroserie>
        <cantidad>20</cantidad>
        <peso>100</peso>
    </pedido>
</pedidos>
